language: php

php:
  - 5.3
  - 5.4

before_install:
  - composer install
  - rm -rf vendor/meido/html
  - git clone git://github.com/Anahkiasen/html.git vendor/meido/html
  - php artisan asset:publish anahkiasen/cerberus

script: phpunit